version: "3.9"
services:
  
  node_backend:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    image: backend:latest
    build: ./
    container_name: backend.container
    entrypoint: sh ./scripts/start_node.sh
    hostname: 0.0.0.0
    ports: 
      - "3000:3000"
    volumes: 
      - ./:/app
    environment:
      MONGO_URI : mongodb://root:example@mongo:27017
    depends_on: 
      - mongo
  
  mongo:
    image: mongo
    restart: always
    container_name: mongo.container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - './mongodb:/data/db'
    ports:
      - 27017:27017
    expose: 
      - 27017


networks: 
  ernmy_stack:
    driver: bridge



# sudo chown -R $USER:$(id -gn $USER) ./*