version: "3.9"
services:
  
  node_backend:
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      image: node_backend:latest
      build: ./node_backend
      container_name: node_backend.container
      entrypoint: sh start_node.sh
      hostname: 0.0.0.0
      ports: 
        - "3000:3000"
      volumes: 
        - ./node_backend/:/app
      depends_on: 
        - mongo
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - './mongodb:/data/db'
    ports:
      - 27017:27017
    expose: 
      - 27017


networks: 
  ernmy_stack:
    driver: bridge



# sudo chown -R $USER:$(id -gn $USER) ./*